---
title: Ngocbh.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Ngoc Bui
url: ''
baseurl: ''
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
new_size: 10
disqus:
  shortname: ngocjr7
  public_key: 0FfcM93k8k3fn8vFYR7OTWLPbUbEUqQRT7H2m9Dtzhr5p0W4TtGeAYWgIBfW3gBv
source: "."
destination: "./_site"
sass:
  style: :compressed
  sass_dir: assets/css/
